### ISSUE TITLE
Zero collision?

### ISSUE THREAD

**Issue by Johncook2** [twestpha/DredgeDeepSubmergence#3]
For some reason one of my saves has zero collision with the submarine, but all my other saves have collision. The only difference I can think of is that I created the save file with dredge hardmode and Deep Submergence installed.

**Comment by Johncook2** [comment]
![Screenshot 2024-09-01 183101](https://github.com/user-attachments/assets/e211b7b9-f7d6-48c6-ad53-cd1c40b00348)

**Comment by twestpha** [comment]
Should be fixed in 0.3.0!
